[2021-06-25 18:06:33.0432] [ERROR] Telegram.Bot.Exceptions.ApiRequestException: Bad Request: message to delete not found
   в Telegram.Bot.TelegramBotClient.<MakeRequestAsync>d__54`1.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   в porulyu.BotMain.Services.OperationsBot.<DeleteMessage>d__57.MoveNext() в C:\Users\thedr\Desktop\Works\StartUps\porulyu\porulyu.BotMain\Services\OperationsBot.cs:строка 2154
[2021-06-25 18:47:40.4349] [ERROR] System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в porulyu.BotMain.Services.OperationsBot.<BotOnCallbackQueryReceived>d__8.MoveNext() в C:\Users\thedr\Desktop\Works\StartUps\porulyu\porulyu.BotMain\Services\OperationsBot.cs:строка 188
[2021-06-25 18:51:57.7276] [ERROR] Пользователь:305613360 Ошибка:Достигнуто максимальное количество фильтров
[2021-06-25 18:52:48.8870] [ERROR] Пользователь:305613360 Ошибка:Достигнуто максимальное количество фильтров
[2021-06-25 18:52:51.1753] [ERROR] Пользователь:305613360 Ошибка:Достигнуто максимальное количество фильтров
[2021-06-25 18:52:56.8530] [ERROR] Пользователь:305613360 Ошибка:Достигнуто максимальное количество фильтров
[2021-06-25 20:09:53.1541] [ERROR] The seed entity for entity type 'Rate' cannot be added because another seed entity with the same key value for {'Id'} has already been added. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
[2021-06-25 20:09:57.5915] [ERROR] Пользователь:1688220224 Ошибка:The seed entity for entity type 'Rate' cannot be added because another seed entity with the same key value for {'Id'} has already been added. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
[2021-06-25 20:10:03.1838] [ERROR] The seed entity for entity type 'Rate' cannot be added because another seed entity with the same key value for {'Id'} has already been added. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
[2021-06-25 20:10:13.2124] [ERROR] The seed entity for entity type 'Rate' cannot be added because another seed entity with the same key value for {'Id'} has already been added. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
[2021-06-25 20:10:17.0166] [ERROR] Пользователь:305613360 Ошибка:The seed entity for entity type 'Rate' cannot be added because another seed entity with the same key value for {'Id'} has already been added. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
[2021-06-25 20:10:23.2395] [ERROR] The seed entity for entity type 'Rate' cannot be added because another seed entity with the same key value for {'Id'} has already been added. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
[2021-06-25 20:10:33.2562] [ERROR] The seed entity for entity type 'Rate' cannot be added because another seed entity with the same key value for {'Id'} has already been added. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
[2021-06-25 20:10:43.2787] [ERROR] The seed entity for entity type 'Rate' cannot be added because another seed entity with the same key value for {'Id'} has already been added. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
[2021-06-25 20:17:06.6508] [ERROR] Пользователь:305613360 Ошибка:В базе данных уже существует объект с именем "Rates".
[2021-06-25 20:27:30.5727] [ERROR] Telegram.Bot.Exceptions.ApiRequestException: Bad Request: message to delete not found
   в Telegram.Bot.TelegramBotClient.<MakeRequestAsync>d__54`1.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   в porulyu.BotMain.Services.OperationsBot.<DeleteMessage>d__60.MoveNext() в C:\Users\thedr\Desktop\Works\StartUps\porulyu\porulyu.BotMain\Services\OperationsBot.cs:строка 2359
[2021-06-25 20:39:23.0157] [ERROR] System.ArgumentOutOfRangeException: Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции.
Имя параметра: index
   в System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   в System.Collections.Generic.List`1.get_Item(Int32 index)
   в porulyu.BotMain.Services.OperationsCreateMessagesBot.GetMyReportsButtons(User user) в C:\Users\thedr\Desktop\Works\StartUps\porulyu\porulyu.BotMain\Services\OperationsCreateMessagesBot.cs:строка 1066
   в porulyu.BotMain.Services.OperationsBot.<SendMyReports>d__51.MoveNext() в C:\Users\thedr\Desktop\Works\StartUps\porulyu\porulyu.BotMain\Services\OperationsBot.cs:строка 2086
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   в porulyu.BotMain.Services.OperationsBot.<BotOnCallbackQueryReceived>d__8.MoveNext() в C:\Users\thedr\Desktop\Works\StartUps\porulyu\porulyu.BotMain\Services\OperationsBot.cs:строка 302
[2021-06-25 21:45:36.5393] [ERROR] Не удается выполнить привязки исполняющей среды по нулевой ссылке
[2021-06-25 21:46:38.4710] [ERROR] Не удается выполнить привязки исполняющей среды по нулевой ссылке
[2021-06-25 21:47:52.7113] [ERROR] Не удается выполнить привязки исполняющей среды по нулевой ссылке
[2021-06-25 21:49:19.1054] [ERROR] Не удается выполнить привязки исполняющей среды по нулевой ссылке
[2021-06-25 21:49:29.1834] [ERROR] Не удается выполнить привязки исполняющей среды по нулевой ссылке
[2021-06-25 21:49:39.2581] [ERROR] Не удается выполнить привязки исполняющей среды по нулевой ссылке
[2021-06-25 21:49:49.3527] [ERROR] Не удается выполнить привязки исполняющей среды по нулевой ссылке
